apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-test
spec:
  entrypoint: pipeline
  #prepare a volume claim for the entire workflow
  volumeClaimTemplates:
    - metadata:
        name: repo-root
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  #start the sequence
  templates:
    - name: pipeline
      steps:
        - - name: check-repo
            template: check-repo
        #todo add other steps later

    - name: check-repo
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          [
            "echo getting message from volume; ls /workdir/gitrepo/mockapi.git > ls.txt; cat ls.txt",
          ]
        volumeMounts:
          - name: repo-root
            mountPath: /workdir ##

      #this is the git fetch magic as an init container in the first step
      initContainers:
        - image: k8s.gcr.io/git-sync:v3.1.6
          args:
            - "--repo=https://github.com/gagandeepsingh1105/mockapi.git"
            - "--root=/workdir/gitrepo"
            - "--max-sync-failures=3"
            - "--timeout=200"
            - "--branch=master"
            - "--one-time"
          name: git-data
          env:
          - name: GITSYNC_USERNAME 
            valueFrom:
              secretKeyRef:
                key: username
                name: git-user-pass
          - name: GITSYNC_PASSWORD 
            valueFrom:
              secretKeyRef:
                key: password
                name: git-user-pass         
          volumeMounts:
            - name: repo-root
              mountPath: /workdir ##

      securityContext:
        runAsUser: 0 # to allow read of ssh key

